name: todo
description: "Todo App"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  animate_do: ^3.1.2
  hexcolor: ^3.0.1
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: mainFont
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
